version: 2.1
orbs:
  pack: buildpacks/pack@0.2.4

executors:
  machine:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: xlarge
    environment:
      CARGO_INCREMENTAL: 0
  docker:
    docker:
      - image: cimg/rust:1.59
    resource_class: xlarge
    working_directory: /mnt/ramdisk/project
    environment:
      CARGO_INCREMENTAL: 0
      TMPDIR: /mnt/ramdisk

commands:
  restore-cargo-cache:
    steps:
      - restore_cache:
          keys:
            # CIRCLE_JOB is the job name, eg 'lint', ensuring caches are job-specific.
            - cargo-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.lock" }}-{{ checksum ".circleci/config.yml" }}
  save-cargo-cache:
    steps:
      - save_cache:
          key: cargo-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.cargo/registry/index
            - ~/.cargo/registry/cache
            - ~/.cargo/git
            - ./target
  install-rust:
    steps:
      - run:
          name: Install Rust
          command: curl https://sh.rustup.rs -sSf | sh -s -- -y
  install-musl-tools:
    steps:
      - run:
          name: Install musl tools
          command: sudo apt-get update && sudo apt-get install musl-tools --no-install-recommends
  install-musl-target:
    steps:
      - run:
          name: Install musl target
          command: rustup target add x86_64-unknown-linux-musl

jobs:
  lint-docker:
    executor: docker
    steps:
      - checkout
      - restore-cargo-cache
      - run:
          name: Clippy
          # Using --all-targets so tests are checked and --deny to fail on warnings.
          command: cargo clippy --all-targets --all-features --locked -- --deny warnings
      - run:
          name: rustfmt
          command: cargo fmt -- --check --verbose
      - save-cargo-cache

  lint-machine:
    executor: machine
    steps:
      - checkout
      - restore-cargo-cache
      - install-rust
      - run:
          name: Clippy
          command: cargo clippy --all-targets --all-features --locked -- --deny warnings
      - run:
          name: rustfmt
          command: cargo fmt -- --check --verbose
      - save-cargo-cache

  unit-test-docker:
    executor: docker
    steps:
      - checkout
      - restore-cargo-cache
      - run:
          name: Run tests
          command: cargo test --all-features --locked
      - save-cargo-cache

  unit-test-machine:
    executor: machine
    steps:
      - checkout
      - restore-cargo-cache
      - install-rust
      - run:
          name: Run tests
          command: cargo test --all-features --locked
      - save-cargo-cache

  integration-test-docker:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - restore-cargo-cache
      - install-musl-tools
      - install-musl-target
      - pack/install-pack:
          version: 0.24.0
      - run:
          name: Run tests
          command: cargo test --all-features --locked -- --ignored
      - save-cargo-cache

  integration-test-machine:
    executor: machine
    steps:
      - checkout
      - restore-cargo-cache
      - install-rust
      - install-musl-tools
      - install-musl-target
      - pack/install-pack:
          version: 0.24.0
      - run:
          name: Run tests
          command: cargo test --all-features --locked -- --ignored
      - save-cargo-cache

  all-tests-docker:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - restore-cargo-cache
      - install-musl-tools
      - install-musl-target
      - pack/install-pack:
          version: 0.24.0
      - run:
          name: Run tests
          command: cargo test --all-features --locked -- --include-ignored
      - save-cargo-cache

  all-tests-machine:
    executor: machine
    steps:
      - checkout
      - restore-cargo-cache
      - install-rust
      - install-musl-tools
      - install-musl-target
      - pack/install-pack:
          version: 0.24.0
      - run:
          name: Run tests
          command: cargo test --all-features --locked -- --include-ignored
      - save-cargo-cache

workflows:
  ci:
    jobs:
      - lint-docker
      - lint-machine
      - unit-test-docker
      - unit-test-machine
      - integration-test-docker
      - integration-test-machine
      - all-tests-docker
      - all-tests-machine
